package org.scalaide.play2.routeeditor.properties

import org.scalaide.play2.properties.SyntaxColouringTreeContentAndLabelProvider
import org.scalaide.play2.routeeditor.RouteSyntaxClasses

object RouteSyntaxColouringTreeContentAndLabelProvider extends SyntaxColouringTreeContentAndLabelProvider(RouteSyntaxClasses.categories)