package org.scalaide.play2.templateeditor.properties

import org.scalaide.play2.properties.SyntaxColouringTreeContentAndLabelProvider
import org.scalaide.play2.templateeditor.TemplateSyntaxClasses

object TemplateSyntaxColouringTreeContentAndLabelProvider extends SyntaxColouringTreeContentAndLabelProvider(TemplateSyntaxClasses.categories)