package org.scalaide.play2.properties

import org.scalaide.play2.templateeditor.TemplateSyntaxClasses

object TemplateSyntaxColouringTreeContentAndLabelProvider extends SyntaxColouringTreeContentAndLabelProvider(TemplateSyntaxClasses.categories)